### ISSUE TITLE
ERROR Error: Uncaught (in promise): Error: Failed to scan code.

### ISSUE THREAD

**Issue by eallan33** [robingenz/ionic-capacitor-barcode-scanner#1] opened 2023-06-30 14:17 UTC
Good morning, I have cloned your project, followed every step, built and run on my device, and it worked perfectly, but since 3 days now I can't scan any QR or barcode, simply when I click on FAB, the camera doesn't start.

![Captura de Pantalla 2023-06-30 a la(s) 10 13 57 a  m](https://github.com/robingenz/ionic-capacitor-barcode-scanner/assets/15183745/58018d69-dadc-48b1-9aca-da870b130ef3)

The only that I remember is that my Android Studio update the Gradle version to 8.0.2

Thanks in advance for your support
Eduardo Allan

**Comment by robingenz** [comment] 2023-06-30 14:24
Thank you for your request! 
I close this as duplicate of https://github.com/capawesome-team/capacitor-mlkit/issues/38

**Closed as not planned** 2023-06-30 14:24 UTC
